package com.example.util

import android.content.Context
import android.content.Intent
import com.example.data.model.InvoiceEntity
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.*

/**
 * Builds a formatted plain-text invoice summary suitable for sharing
 * via WhatsApp, Email, SMS, or any other Android share target.
 */
object InvoiceShareHelper {

    /**
     * Build a comprehensive GST-compliant invoice text for sharing.
     */
    fun buildInvoiceText(invoice: InvoiceEntity, businessName: String = "GrowthEngine Industrial Works"): String {
        val currencyFmt = NumberFormat.getNumberInstance(Locale.forLanguageTag("en-IN")).apply {
            maximumFractionDigits = 2
        }
        val dateFmt = SimpleDateFormat("dd MMM yyyy", Locale.forLanguageTag("en-IN"))

        val taxType = if (invoice.isInterState) "IGST" else "CGST + SGST"
        val taxAmount = if (invoice.isInterState) {
            "IGST (18%): ₹${currencyFmt.format(invoice.igstAmount)}"
        } else {
            "CGST (9%): ₹${currencyFmt.format(invoice.cgstAmount)}\nSGST (9%): ₹${currencyFmt.format(invoice.sgstAmount)}"
        }

        val statusEmoji = when (invoice.paymentStatus) {
            "PAID" -> "✅"
            "PARTIAL" -> "🟡"
            "OVERDUE" -> "🔴"
            else -> "⏳"
        }

        val eWayLine = if (!invoice.eWayBillNumber.isNullOrBlank()) {
            "\ne-Way Bill: ${invoice.eWayBillNumber}"
        } else ""

        val notesLine = if (!invoice.notes.isNullOrBlank()) {
            "\n\n📝 Notes: ${invoice.notes}"
        } else ""

        return """
            |━━━━━━━━━━━━━━━━━━━━━━━━━━━
            |  $businessName
            |  GST TAX INVOICE [RULE 46]
            |━━━━━━━━━━━━━━━━━━━━━━━━━━━
            |
            |Invoice No: ${invoice.invoiceNumber}
            |Date: ${dateFmt.format(Date(invoice.dateEpoch))}
            |Due Date: ${dateFmt.format(Date(invoice.dueDateEpoch))}$eWayLine
            |
            |BILLED TO:
            |${invoice.partyName}
            |GSTIN: ${invoice.partyGstin}
            |Place of Supply: ${invoice.partyState}
            |Contact: ${invoice.partyPhone}
            |
            |─────────────────────────────
            |ITEMS:
            |${invoice.itemsSummary} (${invoice.itemsCount} items)
            |
            |Taxable Amount: ₹${currencyFmt.format(invoice.subtotal)}
            |$taxAmount
            |─────────────────────────────
            |TOTAL: ₹${currencyFmt.format(invoice.totalAmount)}
            |Amount Paid: ₹${currencyFmt.format(invoice.amountPaid)}
            |Balance Due: ₹${currencyFmt.format(invoice.balanceDue)} $statusEmoji ${invoice.paymentStatus}
            |─────────────────────────────
            |
            |BANK DETAILS:
            |Bank: HDFC Bank (Industrial Branch)
            |A/C: 50200049102 | IFSC: HDFC0001245
            |UPI: growthengine@hdfcbank$notesLine
            |
            |━━━━━━━━━━━━━━━━━━━━━━━━━━━
            |Generated by GrowthEngine ERP
        """.trimMargin()
    }

    /**
     * Launch an Android share intent with the invoice text.
     * Lets the user pick WhatsApp, Email, SMS, etc.
     */
    fun shareInvoice(context: Context, invoice: InvoiceEntity, businessName: String = "GrowthEngine Industrial Works") {
        val text = buildInvoiceText(invoice, businessName)
        val subject = "Invoice ${invoice.invoiceNumber} — ₹${
            NumberFormat.getNumberInstance(Locale.forLanguageTag("en-IN")).apply {
                maximumFractionDigits = 0
            }.format(invoice.totalAmount)
        } | $businessName"

        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, subject)
            putExtra(Intent.EXTRA_TEXT, text)
        }

        val chooser = Intent.createChooser(shareIntent, "Share Invoice via")
        chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chooser)
    }

    /**
     * Share invoice directly via WhatsApp if installed.
     * Falls back to the generic chooser if WhatsApp is not available.
     */
    fun shareViaWhatsApp(context: Context, invoice: InvoiceEntity, phoneNumber: String? = null, businessName: String = "GrowthEngine Industrial Works") {
        val text = buildInvoiceText(invoice, businessName)

        val waIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            setPackage("com.whatsapp")
            putExtra(Intent.EXTRA_TEXT, text)
        }

        try {
            context.startActivity(waIntent)
        } catch (e: Exception) {
            // WhatsApp not installed, fall back to generic share
            shareInvoice(context, invoice, businessName)
        }
    }
}
